name: Update Data

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Clone Foundry data
        uses: actions/checkout@v4
        with:
          repository: foundryvtt/pf2e
          path: ./pf2e
      - name: Update Data
        run: |
          ./update.sh
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "[no ci] Update Data"